DROP DATABASE IF EXISTS HELADERIA;
CREATE DATABASE HELADERIA;
USE HELADERIA;

CREATE TABLE MEDIDA(
cveMedida CHAR(1) PRIMARY KEY NOT NULL,
nomMedida VARCHAR(25) NOT NULL
);
CREATE TABLE SABOR(
cveSab CHAR(6) PRIMARY KEY NOT NULL,
nomSab VARCHAR(25) NOT NULL,
cveMedida CHAR(1) NOT NULL,
FOREIGN KEY (cveMedida) REFERENCES MEDIDA (cveMedida)
ON UPDATE CASCADE
);
INSERT INTO MEDIDA VALUES('G','GRANDE');
INSERT INTO MEDIDA VALUES('M','MEDIANO');
INSERT INTO MEDIDA VALUES('C','CHICO');